apiVersion: v1
kind: Service
metadata:
  name: backend-svc # Service 이름 (다른 Pod들이 이 이름으로 backend에 접근)
  namespace: jeonbongjun
  annotations:
    cloud.google.com/neg: '{"ingress": true}' # GKE Ingress와 연동하기 위한 어노테이션
    cloud.google.com/backend-config: '{"default": "backend-health-config"}' # BackendConfig 참조
spec:
  selector:
    app: backend # 이 Service가 연결될 Pod를 식별하는 라벨 (Deployment의 Pod 라벨과 일치)
  ports:
    - protocol: TCP
      port: 8080 # Service가 노출할 포트
      targetPort: 8080 # Pod의 컨테이너 포트 (Deployment의 containerPort와 일치)
  type: ClusterIP # 클러스터 내부에서만 접근 가능한 타입