name: Build and Push Backend Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  # --- Docker Hub 설정 (!! 반드시 실제 값으로 수정 !!) ---
  DOCKERHUB_USERNAME: o11117 # 실제 Docker Hub 사용자 ID
  IMAGE_NAME: backend                         # 이 저장소에서 빌드할 이미지 이름 (예: backend)

jobs:
  build-and-push:
    name: Build and Push Backend Image
    runs-on: ubuntu-latest
    # permissions 제거 또는 수정 (GCP 관련 id-token 불필요)

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # --- [ Docker Hub 로그인으로 수정 ] ---
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }} # GitHub Secret 필요
          password: ${{ secrets.DOCKERHUB_TOKEN }}  # GitHub Secret 필요

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Generate Image Tag
        id: image_tag
        run: echo "TAG=$(echo $GITHUB_SHA | head -c7)" >> $GITHUB_OUTPUT

      # --- [ 이미지 태그 경로 수정 ] ---
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true

          tags: |
            ${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest
            ${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          platforms: linux/amd64,linux/arm64